version: '2'
services:
  api: 
    build: ./api # specify the directory of the Dockerfile
    ports:
    - "8080:8080" #specify ports forwarding
    links:
    - database # link this service to the database service
    # volumes:
    # - .:/usr/src/app
    depends_on:
    - database
    environment: 
      - MONGO_DB=database
      - DEFAULT_PORT=8080
      - URL_PREFIX=pbid.io
  database:
    image: mongo # specify image to build container from
    ports:
    - "27017:27017"    
  app: 
    build: ./app # specify the directory of the Dockerfile
    ports:
    - "3000:3000" #specify ports forwarding
    links:
    - api # link this service to the database service
    depends_on:
    - api
    environment: 
      - MONGO_DB=database
      - PORT=3000
      - URL_PREFIX=pbid.io



