version: '2'
services:
  app: 
    build: ./ # specify the directory of the Dockerfile
    ports:
    - "8080:8080" #specify ports forwarding
    links:
    - database # link this service to the database service
    # volumes:
    # - .:/usr/src/app
    depends_on:
    - database
  database:
    image: mongo # specify image to build container from
    ports:
    - "27017:27017"